services:

  oasees_portal:
    build:
      context: ./portal
    ports:
      - "3000:3000"

    env_file:
      - .env

    command: >
          /bin/sh -c '
          echo "REACT_APP_INFRA_HOST=$INFRA_HOST:6001" > /oasees_portal/.env >> /oasees_portal/.env
          && echo "REACT_APP_BLOCKCHAIN_ADDRESS=$INFRA_HOST:8545" >> /oasees_portal/.env
          && echo "REACT_APP_IPFS_HOST=$IPFS_HOST:5001" >> /oasees_portal/.env
          && npm start
          '

    stop_grace_period: 3s

    container_name: oasees_portal

  oasees_blockchain:
    build: ./hardhat_node
    container_name: hardhat
    ports:
      - "8545:8545"

  oasees_ipfs:
    build: ./ipfs_node
    container_name: ipfs
    env_file:
      - .env
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"



  flask_notebooks_api:
    build:
      context: ./jupyter_provider
    depends_on:
      oasees_blockchain:
        condition: service_started
      oasees_ipfs:
        condition: service_started
    ports:
      - "6001:6001"  
    env_file:
      - .env

    container_name: flask_notebooks_api 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 


